import type { AppData, EventItem, NotificationLogEntry, TaskItem } from '../types'
import { addDaysISO, formatDurationMinutes, listDatesBetween, timeToMinutes, todayISO } from './dateUtils'
import { makeId } from './id'
import { eventOccursOnDate } from './availability'

const LOOKBACK_DAYS = 2
const LOOKAHEAD_DAYS = 180
const FRESH_WINDOW_MS = 5 * 60 * 1000

export interface DueReminder {
  fireKey: string
  itemKind: 'event' | 'task' | 'study'
  itemId: string
  message: string
  dueAt: Date
  fresh: boolean
}

function occurrenceDatesForEvent(event: EventItem, now: Date): string[] {
  const windowStart = addDaysISO(todayISO(), -LOOKBACK_DAYS)
  const windowEnd = addDaysISO(todayISO(), LOOKAHEAD_DAYS)
  if (event.recurrence?.freq === 'weekly') {
    const rangeStart = event.date > windowStart ? event.date : windowStart
    const rangeEnd = event.recurrence.until && event.recurrence.until < windowEnd ? event.recurrence.until : windowEnd
    if (rangeStart > rangeEnd) return []
    return listDatesBetween(rangeStart, rangeEnd).filter((d) => eventOccursOnDate(event, d))
  }
  if (event.date < windowStart || event.date > windowEnd) return []
  return [event.date]
}

function eventDueDate(event: EventItem, occurrenceDate: string): Date {
  const time = event.startTime ?? '09:00'
  const [h, m] = time.split(':').map(Number)
  const d = new Date(occurrenceDate + 'T00:00:00')
  d.setHours(h, m, 0, 0)
  return d
}

export function computeDueReminders(data: AppData, now: Date): DueReminder[] {
  const out: DueReminder[] = []

  for (const event of data.events) {
    const occurrences = occurrenceDatesForEvent(event, now)
    for (const occ of occurrences) {
      const baseDate = eventDueDate(event, occ)
      for (const offset of event.reminders) {
        const dueAt = new Date(baseDate.getTime() - offset * 60000)
        if (dueAt > now) continue
        const fireKey = `${event.id}:${occ}:${offset}`
        if (event.remindersFired?.includes(fireKey)) continue
        out.push({
          fireKey,
          itemKind: 'event',
          itemId: event.id,
          message: reminderMessage(event.title, offset, event.type),
          dueAt,
          fresh: now.getTime() - dueAt.getTime() <= FRESH_WINDOW_MS,
        })
      }
    }
  }

  for (const task of data.tasks) {
    if (!task.dueDate || task.status === 'completada') continue
    const offsets = task.reminders ?? data.settings.defaultTaskReminders
    const baseDate = new Date(task.dueDate + 'T09:00:00')
    for (const offset of offsets) {
      const dueAt = new Date(baseDate.getTime() - offset * 60000)
      if (dueAt > now) continue
      const fireKey = `${task.id}:${task.dueDate}:${offset}`
      if (task.remindersFired?.includes(fireKey)) continue
      out.push({
        fireKey,
        itemKind: 'task',
        itemId: task.id,
        message: `⏰ "${task.title}" vence ${offset >= 1440 ? `en ${Math.round(offset / 1440)} día(s)` : `en ${offset} min`}.`,
        dueAt,
        fresh: now.getTime() - dueAt.getTime() <= FRESH_WINDOW_MS,
      })
    }

    // daily "you should study X today" nudge for auto-generated study sessions
    if (task.isAutoGenerated && task.scheduledDate) {
      const morningTrigger = new Date(task.scheduledDate + 'T08:00:00')
      if (morningTrigger <= now) {
        const fireKey = `studyday:${task.id}:${task.scheduledDate}`
        if (!task.remindersFired?.includes(fireKey)) {
          out.push({
            fireKey,
            itemKind: 'study',
            itemId: task.id,
            message: `📚 Hoy deberías estudiar ${formatDurationMinutes(task.estimatedMinutes)} para "${task.title.replace(/^Estudiar para /, '')}".`,
            dueAt: morningTrigger,
            fresh: now.getTime() - morningTrigger.getTime() <= FRESH_WINDOW_MS,
          })
        }
      }
    }
  }

  return out
}

function reminderMessage(title: string, offsetMinutes: number, type: string): string {
  const icon = type === 'examen' ? '📚' : type === 'entrega' ? '📤' : '🔔'
  if (offsetMinutes >= 1440) {
    const days = Math.round(offsetMinutes / 1440)
    if (days === 1) return `${icon} Mañana tienes: ${title}`
    if (days % 7 === 0) return `${icon} Dentro de ${days / 7} semana(s) tienes: ${title}`
    return `${icon} Dentro de ${days} días tienes: ${title}`
  }
  if (offsetMinutes >= 60) return `${icon} Dentro de ${Math.round(offsetMinutes / 60)} h: ${title}`
  return `${icon} Dentro de ${offsetMinutes} min: ${title}`
}

export function applyDueReminders(
  data: AppData,
  due: DueReminder[]
): { events: EventItem[]; tasks: TaskItem[]; notificationLog: NotificationLogEntry[]; fresh: DueReminder[] } {
  const eventFired = new Map<string, string[]>()
  const taskFired = new Map<string, string[]>()

  for (const d of due) {
    if (d.itemKind === 'event') {
      eventFired.set(d.itemId, [...(eventFired.get(d.itemId) ?? []), d.fireKey])
    } else {
      taskFired.set(d.itemId, [...(taskFired.get(d.itemId) ?? []), d.fireKey])
    }
  }

  const events = data.events.map((e) =>
    eventFired.has(e.id) ? { ...e, remindersFired: [...(e.remindersFired ?? []), ...eventFired.get(e.id)!] } : e
  )
  const tasks = data.tasks.map((t) =>
    taskFired.has(t.id) ? { ...t, remindersFired: [...(t.remindersFired ?? []), ...taskFired.get(t.id)!] } : t
  )

  const newLogEntries: NotificationLogEntry[] = due.map((d) => ({
    id: makeId(),
    message: d.message,
    timestamp: new Date().toISOString(),
    read: false,
  }))

  const notificationLog = [...newLogEntries, ...data.notificationLog].slice(0, 200)

  return { events, tasks, notificationLog, fresh: due.filter((d) => d.fresh) }
}

export function requestNotificationPermission(): Promise<NotificationPermission> {
  if (typeof Notification === 'undefined') return Promise.resolve('denied')
  return Notification.requestPermission()
}

export function pushBrowserNotification(message: string) {
  if (typeof Notification === 'undefined') return
  if (Notification.permission === 'granted') {
    try {
      new Notification('Mi Planificador', { body: message })
    } catch (err) {
      console.warn('No se pudo mostrar la notificación', err)
    }
  }
}
