import type { AppData, EventItem, Goal, Importance, TaskItem } from '../types'
import { addDaysISO, formatDurationMinutes, listDatesBetween, minutesToTime, timeToMinutes, todayISO, getWeekday } from './dateUtils'
import { getFreeBlocksForDate, getFreeMinutesForDate, getEventsForDate } from './availability'
import { makeId } from './id'
import type { Interval } from './intervals'

// ---------------------------------------------------------------------------
// 1. Water-filling distribution: spread `totalMinutes` across candidate days
//    as evenly as possible, respecting each day's capacity, without dumping
//    everything on the last day.
// ---------------------------------------------------------------------------

export interface DayCapacity {
  date: string
  capacityMinutes: number
}

export interface DistributionResult {
  allocations: { date: string; minutes: number }[]
  shortfallMinutes: number
  totalAllocated: number
}

const ROUND_CHUNK = 5

export function distributeMinutes(totalNeeded: number, days: DayCapacity[], dailyCapPerTask: number): DistributionResult {
  let remaining = totalNeeded
  const state = days.map((d) => ({ date: d.date, minutes: 0, cap: Math.max(0, Math.min(d.capacityMinutes, dailyCapPerTask)) }))
  let active = state.filter((s) => s.cap > 0)

  while (remaining > 0 && active.length > 0) {
    const share = Math.max(ROUND_CHUNK, Math.ceil(remaining / active.length / ROUND_CHUNK) * ROUND_CHUNK)
    let progressed = false
    for (const s of active) {
      if (remaining <= 0) break
      const add = Math.min(share, s.cap - s.minutes, remaining)
      if (add > 0) {
        s.minutes += add
        remaining -= add
        progressed = true
      }
    }
    active = active.filter((s) => s.minutes < s.cap)
    if (!progressed) break
  }

  return {
    allocations: state.filter((s) => s.minutes > 0).map((s) => ({ date: s.date, minutes: s.minutes })),
    shortfallMinutes: Math.max(0, remaining),
    totalAllocated: totalNeeded - Math.max(0, remaining),
  }
}

// ---------------------------------------------------------------------------
// 2. Study plan for an exam/delivery: build candidate days, distribute hours,
//    materialize them as auto-generated 'estudio' tasks.
// ---------------------------------------------------------------------------

export interface StudyPlanRequest {
  event: EventItem
  totalHours: number
  startFrom?: string // ISO, defaults to today
}

export interface StudyPlanOutcome {
  tasks: TaskItem[]
  shortfallMinutes: number
  warning?: string
  candidateDays: number
}

export function buildStudyPlan(data: AppData, req: StudyPlanRequest): StudyPlanOutcome {
  const start = req.startFrom ?? todayISO()
  const lastStudyDay = addDaysISO(req.event.date, -1)
  const allDays = listDatesBetween(start, lastStudyDay)
  const cap = data.settings.maxDailyStudyMinutesPerTask

  const otherAutoTasks = data.tasks.filter((t) => t.linkedEventId !== req.event.id)
  const dataForCapacity: AppData = { ...data, tasks: otherAutoTasks }

  const dayCapacities: DayCapacity[] = allDays.map((date) => ({
    date,
    capacityMinutes: getFreeMinutesForDate(dataForCapacity, date),
  }))

  const totalMinutesNeeded = Math.round(req.totalHours * 60)
  const dist = distributeMinutes(totalMinutesNeeded, dayCapacities, cap)

  const tasks: TaskItem[] = dist.allocations.map(({ date, minutes }) => ({
    id: makeId(),
    kind: 'task',
    title: `Estudiar para ${req.event.title}`,
    category: 'estudio',
    dueDate: req.event.date,
    estimatedMinutes: minutes,
    priority: req.event.importance,
    status: 'pendiente',
    scheduledDate: date,
    linkedEventId: req.event.id,
    isAutoGenerated: true,
    createdAt: new Date().toISOString(),
  }))

  let warning: string | undefined
  if (dist.shortfallMinutes > 0) {
    warning = `⚠️ No tienes suficientes horas disponibles: faltan ${formatDurationMinutes(
      dist.shortfallMinutes
    )} de las ${req.totalHours} h solicitadas antes de "${req.event.title}". Prueba a subir el límite diario de estudio, liberar disponibilidad, o reducir el objetivo de horas.`
  }

  return { tasks, shortfallMinutes: dist.shortfallMinutes, warning, candidateDays: allDays.length }
}

// ---------------------------------------------------------------------------
// 3. Daily planner: place fixed events + pending tasks into free blocks.
// ---------------------------------------------------------------------------

export type ScheduleBlockType = 'event' | 'task' | 'free'

export interface ScheduleBlock {
  type: ScheduleBlockType
  start: string
  end: string
  title: string
  refId?: string
  itemType?: string
  importance?: Importance
}

export interface PlanDayResult {
  blocks: ScheduleBlock[]
  unplaced: { task: TaskItem; reason: string }[]
  freeMinutesLeft: number
}

function priorityScore(t: TaskItem, dateISO: string): number {
  let score = t.priority * 100
  if (t.dueDate) {
    const daysLeft = listDatesBetween(dateISO, t.dueDate).length - 1
    score += Math.max(0, 30 - daysLeft)
  }
  if (t.isAutoGenerated) score += 5
  return score
}

// Counts distinct days this week where the goal's category shows any activity:
// a non-abandoned task of that category (however it was created — via the
// goal's own suggestions or a plain quick-added task), or a calendar event of
// that category (e.g. logging "Gimnasio" as a Deporte event). This makes the
// counter reflect real life instead of only sessions created through the
// "Aceptar propuesta" flow.
export function getUnmetGoalsForWeek(data: AppData, weekDates: string[]): { goal: Goal; sessionsSoFar: number; needed: number }[] {
  const result: { goal: Goal; sessionsSoFar: number; needed: number }[] = []
  for (const goal of data.goals.filter((g) => g.active)) {
    const activeDates = new Set<string>()
    for (const t of data.tasks) {
      if (t.category !== goal.category || t.status === 'no_hecha') continue
      const activeDate = t.completedDate ?? t.scheduledDate
      if (activeDate && weekDates.includes(activeDate)) activeDates.add(activeDate)
    }
    for (const date of weekDates) {
      if (getEventsForDate(data.events, date).some((e) => e.type === goal.category)) activeDates.add(date)
    }
    const sessionsSoFar = activeDates.size
    if (sessionsSoFar < goal.timesPerWeek) {
      result.push({ goal, sessionsSoFar, needed: goal.timesPerWeek - sessionsSoFar })
    }
  }
  return result
}

export function planDay(data: AppData, dateISO: string, extraCandidateTasks: TaskItem[] = []): PlanDayResult {
  const events = getEventsForDate(data.events, dateISO)
  const eventBlocks: ScheduleBlock[] = events
    .filter((e) => e.startTime)
    .map((e) => ({
      type: 'event',
      start: e.travelMinutes ? minutesToTime(timeToMinutes(e.startTime!) - e.travelMinutes) : e.startTime!,
      end: e.endTime ?? minutesToTime(timeToMinutes(e.startTime!) + 60),
      title: e.travelMinutes ? `${e.title} (incl. ${e.travelMinutes} min desplazamiento)` : e.title,
      refId: e.id,
      itemType: e.type,
      importance: e.importance,
    }))

  let freeBlocks: Interval[] = getFreeBlocksForDate(data, dateISO)

  const alreadyScheduledBlocks: ScheduleBlock[] = data.tasks
    .filter((t) => t.scheduledDate === dateISO && t.scheduledStart && t.scheduledEnd && t.status !== 'completada')
    .map((t) => ({
      type: 'task',
      start: t.scheduledStart!,
      end: t.scheduledEnd!,
      title: t.title,
      refId: t.id,
      itemType: t.category,
      importance: t.priority,
    }))

  const candidateTasks = [
    ...data.tasks.filter((t) => t.scheduledDate === dateISO && t.status !== 'completada' && !t.scheduledStart),
    ...extraCandidateTasks,
  ].sort((a, b) => priorityScore(b, dateISO) - priorityScore(a, dateISO))

  const breakMin = data.settings.breakMinutes
  const placedBlocks: ScheduleBlock[] = []
  const unplaced: { task: TaskItem; reason: string }[] = []

  for (const task of candidateTasks) {
    const needed = task.estimatedMinutes
    // best-fit: choose the smallest free block that can fit the task
    const fitting = freeBlocks
      .map((b, idx) => ({ idx, size: b.end - b.start }))
      .filter((b) => b.size >= needed)
      .sort((a, b) => a.size - b.size)

    if (fitting.length > 0) {
      const idx = fitting[0].idx
      const block = freeBlocks[idx]
      const start = block.start
      const end = start + needed
      placedBlocks.push({
        type: 'task',
        start: minutesToTime(start),
        end: minutesToTime(end),
        title: task.title,
        refId: task.id,
        itemType: task.category,
        importance: task.priority,
      })
      const remainderStart = end + breakMin
      const newBlocks = [...freeBlocks]
      if (remainderStart < block.end) {
        newBlocks[idx] = { start: remainderStart, end: block.end }
      } else {
        newBlocks.splice(idx, 1)
      }
      freeBlocks = newBlocks
      continue
    }

    // try splitting across the two largest blocks if the task is long enough to split usefully
    const sorted = [...freeBlocks].sort((a, b) => b.end - b.start - (a.end - a.start))
    const totalAvail = sorted.reduce((s, b) => s + (b.end - b.start), 0)
    if (sorted.length >= 1 && totalAvail >= needed && needed > 60) {
      let remainingNeed = needed
      const usedIdx: number[] = []
      for (let i = 0; i < freeBlocks.length && remainingNeed > 0; i++) {
        const b = freeBlocks[i]
        const size = b.end - b.start
        if (size <= 0) continue
        const take = Math.min(size, remainingNeed)
        if (take < 20) continue
        placedBlocks.push({
          type: 'task',
          start: minutesToTime(b.start),
          end: minutesToTime(b.start + take),
          title: `${task.title} (parte)`,
          refId: task.id,
          itemType: task.category,
          importance: task.priority,
        })
        remainingNeed -= take
        usedIdx.push(i)
        freeBlocks[i] = { start: b.start + take + breakMin, end: b.end }
      }
      freeBlocks = freeBlocks.filter((b) => b.end - b.start > 0)
      if (remainingNeed > 0) {
        unplaced.push({ task, reason: `Solo cupo parte de "${task.title}" hoy; faltan ${formatDurationMinutes(remainingNeed)}.` })
      }
      continue
    }

    unplaced.push({ task, reason: `No hay un hueco de ${formatDurationMinutes(needed)} libre hoy para "${task.title}".` })
  }

  const freeMinutesLeft = freeBlocks.reduce((s, b) => s + (b.end - b.start), 0)
  const freeAsBlocks: ScheduleBlock[] = freeBlocks
    .filter((b) => b.end - b.start >= 15)
    .map((b) => ({ type: 'free', start: minutesToTime(b.start), end: minutesToTime(b.end), title: 'Tiempo libre' }))

  const all = [...eventBlocks, ...alreadyScheduledBlocks, ...placedBlocks, ...freeAsBlocks].sort(
    (a, b) => timeToMinutes(a.start) - timeToMinutes(b.start)
  )

  return { blocks: all, unplaced, freeMinutesLeft }
}

// ---------------------------------------------------------------------------
// 4. Goal slot suggestion: propose N sessions this week for a recurring goal.
// ---------------------------------------------------------------------------

export interface GoalSuggestion {
  date: string
  start: string
  end: string
}

export function suggestGoalSlots(data: AppData, goal: Goal, weekDates: string[], sessionsAlreadyPlanned: number): GoalSuggestion[] {
  const needed = Math.max(0, goal.timesPerWeek - sessionsAlreadyPlanned)
  if (needed === 0) return []
  const suggestions: GoalSuggestion[] = []
  const usedDates = new Set<string>()

  const dayOptions = weekDates
    .filter((d) => d >= todayISO())
    .map((date) => ({ date, free: getFreeBlocksForDate(data, date) }))
    .filter((d) => d.free.some((b) => b.end - b.start >= goal.sessionDurationMinutes))

  // spread across distinct days first
  for (const opt of dayOptions) {
    if (suggestions.length >= needed) break
    if (usedDates.has(opt.date)) continue
    const block = opt.free.find((b) => b.end - b.start >= goal.sessionDurationMinutes)
    if (!block) continue
    suggestions.push({
      date: opt.date,
      start: minutesToTime(block.start),
      end: minutesToTime(block.start + goal.sessionDurationMinutes),
    })
    usedDates.add(opt.date)
  }

  return suggestions
}

// ---------------------------------------------------------------------------
// 5. Reorganization: find the next available slot from "now" for a task.
// ---------------------------------------------------------------------------

export function findNextAvailableSlot(data: AppData, task: TaskItem, fromDate?: string): GoalSuggestion | null {
  const start = fromDate ?? todayISO()
  const horizon = task.dueDate ? task.dueDate : addDaysISO(start, 21)
  const candidates = listDatesBetween(start, horizon)
  for (const date of candidates) {
    const free = getFreeBlocksForDate(data, date, { excludeTaskId: task.id })
    const block = free.find((b) => b.end - b.start >= task.estimatedMinutes)
    if (block) {
      return { date, start: minutesToTime(block.start), end: minutesToTime(block.start + task.estimatedMinutes) }
    }
  }
  return null
}

export function weekdayName(dateISO: string): string {
  const names = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']
  return names[getWeekday(dateISO)]
}

// ---------------------------------------------------------------------------
// 6. Day highlights: the handful of genuinely important things for a given
//    day (exams, entregas, important events, task deadlines, study load),
//    used for the "Hoy" / "Mañana" panel instead of a raw notification log.
// ---------------------------------------------------------------------------

export interface DayHighlight {
  icon: string
  text: string
}

export function getDayHighlights(data: AppData, dateISO: string): DayHighlight[] {
  const highlights: DayHighlight[] = []

  for (const e of getEventsForDate(data.events, dateISO)) {
    if (e.type === 'examen') highlights.push({ icon: '📝', text: `Examen: ${e.title}` })
    else if (e.type === 'entrega') highlights.push({ icon: '📤', text: `Entrega: ${e.title}` })
    else if (e.importance >= 3) highlights.push({ icon: '⚠️', text: e.title })
  }

  const dueTasks = data.tasks.filter((t) => t.dueDate === dateISO && t.status !== 'completada' && !t.linkedEventId)
  for (const t of dueTasks) highlights.push({ icon: '⏰', text: `Vence: ${t.title}` })

  const studyMinutes = data.tasks
    .filter((t) => t.scheduledDate === dateISO && t.category === 'estudio' && t.status !== 'completada')
    .reduce((sum, t) => sum + t.estimatedMinutes, 0)
  if (studyMinutes > 0) highlights.push({ icon: '📚', text: `Estudiar ${formatDurationMinutes(studyMinutes)}` })

  return highlights
}
