export type ItemType =
  | 'universidad'
  | 'examen'
  | 'entrega'
  | 'practica'
  | 'estudio'
  | 'trabajo'
  | 'deporte'
  | 'ingles'
  | 'viaje'
  | 'cita'
  | 'personal'
  | 'otro'

export const ITEM_TYPES: { value: ItemType; label: string; emoji: string }[] = [
  { value: 'universidad', label: 'Universidad', emoji: '🎓' },
  { value: 'examen', label: 'Examen', emoji: '📝' },
  { value: 'entrega', label: 'Entrega', emoji: '📤' },
  { value: 'practica', label: 'Práctica', emoji: '🧪' },
  { value: 'estudio', label: 'Estudio', emoji: '📚' },
  { value: 'trabajo', label: 'Trabajo', emoji: '💼' },
  { value: 'deporte', label: 'Deporte', emoji: '🏃' },
  { value: 'ingles', label: 'Inglés', emoji: '🇬🇧' },
  { value: 'viaje', label: 'Viaje', emoji: '✈️' },
  { value: 'cita', label: 'Cita', emoji: '🗓️' },
  { value: 'personal', label: 'Personal', emoji: '🏠' },
  { value: 'otro', label: 'Otro', emoji: '•' },
]

export type Importance = 1 | 2 | 3 | 4

export const IMPORTANCE_LABELS: Record<Importance, string> = {
  1: 'Baja',
  2: 'Media',
  3: 'Alta',
  4: 'Crítica',
}

// minutes-before-start values for reminders
export const REMINDER_OPTIONS = [
  { value: 30240, label: '3 semanas antes' },
  { value: 20160, label: '2 semanas antes' },
  { value: 10080, label: '1 semana antes' },
  { value: 4320, label: '3 días antes' },
  { value: 1440, label: '1 día antes' },
  { value: 60, label: '1 hora antes' },
  { value: 15, label: '15 minutos antes' },
]

export interface RecurrenceRule {
  freq: 'weekly'
  daysOfWeek: number[] // 0=domingo ... 6=sábado
  until?: string // ISO date, inclusive
}

export interface EventItem {
  id: string
  kind: 'event'
  title: string
  type: ItemType
  date: string // ISO yyyy-MM-dd, start date
  endDate?: string // for multi-day events
  startTime?: string // 'HH:mm'; undefined = all-day
  endTime?: string
  location?: string
  travelMinutes?: number
  notes?: string
  recurrence?: RecurrenceRule
  excludedDates?: string[] // occurrence dates (ISO) skipped from a recurring event
  importance: Importance
  reminders: number[]
  createdAt: string
  remindersFired?: string[] // ids of fired reminder instants "eventId:offset:occurrenceDate"
}

export type TaskStatus = 'pendiente' | 'en_progreso' | 'completada' | 'no_hecha'

export interface TaskItem {
  id: string
  kind: 'task'
  title: string
  category: ItemType
  dueDate?: string // ISO date deadline
  estimatedMinutes: number
  priority: Importance
  status: TaskStatus
  scheduledDate?: string
  scheduledStart?: string
  scheduledEnd?: string
  notes?: string
  linkedEventId?: string // e.g. exam this study session belongs to
  isAutoGenerated?: boolean
  goalId?: string
  reminders?: number[] // if unset and dueDate present, settings.defaultTaskReminders apply
  createdAt: string
  remindersFired?: string[]
}

export interface Goal {
  id: string
  title: string
  category: ItemType
  timesPerWeek: number
  sessionDurationMinutes: number
  active: boolean
  createdAt: string
}

export interface TimeRange {
  start: string // 'HH:mm'
  end: string
}

export interface AvailabilityTemplate {
  [weekday: number]: TimeRange[] // 0=domingo..6=sábado
}

export interface AvailabilityOverride {
  date: string // ISO
  blocks: TimeRange[] // [] = no disponible ese día
}

export interface AppSettings {
  defaultExamReminders: number[]
  defaultTaskReminders: number[]
  notificationsEnabled: boolean
  breakMinutes: number
  maxDailyStudyMinutesPerTask: number
  dayStart: string
  dayEnd: string
}

export interface NotificationLogEntry {
  id: string
  message: string
  timestamp: string
  read: boolean
}

export interface AppData {
  version: number
  events: EventItem[]
  tasks: TaskItem[]
  goals: Goal[]
  availabilityTemplate: AvailabilityTemplate
  availabilityOverrides: AvailabilityOverride[]
  settings: AppSettings
  notificationLog: NotificationLogEntry[]
}
