import React, { useMemo, useState } from 'react'
import type { EventItem, TaskItem } from '../../types'
import { useData } from '../../context/DataContext'
import { buildStudyPlan, weekdayName } from '../../lib/scheduler'
import { getFreeMinutesForDate } from '../../lib/availability'
import { formatDurationMinutes, formatShort, todayISO } from '../../lib/dateUtils'
import { makeId } from '../../lib/id'

const DURATION_PRESETS = [30, 45, 60, 90, 120, 180]

type Mode = 'auto' | 'manual'

interface ManualEntry {
  id: string
  date: string
  topic: string
  minutes: number
}

export function StudyPlanForm({ event, onDone }: { event: EventItem; onDone: () => void }) {
  const { data, addTasks, removeTasksLinkedTo } = useData()
  const [mode, setMode] = useState<Mode>('auto')
  const [confirmed, setConfirmed] = useState(false)
  const [createdCount, setCreatedCount] = useState(0)

  // --- automatic mode state ---
  const [hours, setHours] = useState(12)
  const autoPreview = useMemo(() => buildStudyPlan(data, { event, totalHours: hours }), [data, event, hours])

  // --- manual mode state ---
  const [entries, setEntries] = useState<ManualEntry[]>([])
  const [entryDate, setEntryDate] = useState(todayISO())
  const [entryTopic, setEntryTopic] = useState('')
  const [entryMinutes, setEntryMinutes] = useState(60)

  const otherTasks = useMemo(() => data.tasks.filter((t) => t.linkedEventId !== event.id), [data.tasks, event.id])

  const remainingFreeForDate = (date: string, excludeEntryId?: string) => {
    const usedByOtherEntries = entries
      .filter((e) => e.date === date && e.id !== excludeEntryId)
      .reduce((s, e) => s + e.minutes, 0)
    const freeThatDay = getFreeMinutesForDate({ ...data, tasks: otherTasks }, date)
    return freeThatDay - usedByOtherEntries
  }

  const addEntry = () => {
    if (entryMinutes <= 0) return
    setEntries((prev) => [...prev, { id: makeId(), date: entryDate, topic: entryTopic.trim(), minutes: entryMinutes }])
    setEntryTopic('')
  }

  const removeEntry = (id: string) => setEntries((prev) => prev.filter((e) => e.id !== id))

  const sortedEntries = [...entries].sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
  const manualTotalMinutes = entries.reduce((s, e) => s + e.minutes, 0)

  const handleConfirmAuto = () => {
    removeTasksLinkedTo(event.id)
    addTasks(autoPreview.tasks)
    setCreatedCount(autoPreview.tasks.length)
    setConfirmed(true)
  }

  const handleConfirmManual = () => {
    if (entries.length === 0) return
    const tasks: TaskItem[] = entries.map((e) => ({
      id: makeId(),
      kind: 'task',
      title: e.topic ? `${e.topic} (${event.title})` : `Estudiar para ${event.title}`,
      category: 'estudio',
      dueDate: event.date,
      estimatedMinutes: e.minutes,
      priority: event.importance,
      status: 'pendiente',
      scheduledDate: e.date,
      linkedEventId: event.id,
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
    }))
    removeTasksLinkedTo(event.id)
    addTasks(tasks)
    setCreatedCount(tasks.length)
    setConfirmed(true)
  }

  if (confirmed) {
    return (
      <div>
        <p style={{ marginBottom: 16 }}>
          ✅ Se han creado {createdCount} sesión(es) de estudio para "{event.title}".
        </p>
        <button className="btn btn-primary" onClick={onDone}>
          Listo
        </button>
      </div>
    )
  }

  return (
    <div>
      <div className="wrap-chips" style={{ marginBottom: 16 }}>
        <button type="button" className={`pill-btn${mode === 'auto' ? ' selected' : ''}`} onClick={() => setMode('auto')}>
          Automático
        </button>
        <button type="button" className={`pill-btn${mode === 'manual' ? ' selected' : ''}`} onClick={() => setMode('manual')}>
          A mi manera
        </button>
      </div>

      {mode === 'auto' ? (
        <>
          <p className="muted" style={{ marginBottom: 14 }}>
            ¿Cuántas horas quieres estudiar en total antes de <strong>{event.title}</strong> ({formatShort(event.date)})? La app las
            reparte por ti entre los días disponibles.
          </p>
          <div className="field">
            <label>Horas totales</label>
            <div className="wrap-chips">
              {[4, 6, 8, 10, 12, 16, 20].map((h) => (
                <button type="button" key={h} className={`pill-btn${hours === h ? ' selected' : ''}`} onClick={() => setHours(h)}>
                  {h} h
                </button>
              ))}
            </div>
            <input
              type="number"
              min={1}
              value={hours}
              onChange={(e) => setHours(Number(e.target.value) || 0)}
              style={{ marginTop: 10 }}
            />
          </div>

          {autoPreview.warning && <div className="warning-box" style={{ marginBottom: 14 }}>{autoPreview.warning}</div>}

          {autoPreview.tasks.length > 0 && (
            <div className="card" style={{ marginBottom: 14 }}>
              <div style={{ fontWeight: 700, marginBottom: 8 }}>Reparto propuesto</div>
              <div className="list-gap">
                {autoPreview.tasks.map((t) => (
                  <div key={t.id} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.88rem' }}>
                    <span>{formatShort(t.scheduledDate!)}</span>
                    <span className="muted">{formatDurationMinutes(t.estimatedMinutes)}</span>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: 10, fontSize: '0.85rem' }} className="muted">
                Total repartido: {formatDurationMinutes(autoPreview.tasks.reduce((s, t) => s + t.estimatedMinutes, 0))}
              </div>
            </div>
          )}

          <button className="btn btn-primary" onClick={handleConfirmAuto} disabled={autoPreview.tasks.length === 0}>
            Confirmar plan de estudio
          </button>
        </>
      ) : (
        <>
          <p className="muted" style={{ marginBottom: 14 }}>
            Elige tú mismo qué día vas a estudiar, qué tema y cuántas horas, para <strong>{event.title}</strong> ({formatShort(event.date)}
            ).
          </p>

          <div className="card" style={{ marginBottom: 14 }}>
            <div className="field">
              <label>Día</label>
              <input type="date" value={entryDate} max={event.date} onChange={(e) => setEntryDate(e.target.value)} />
            </div>
            <div className="field">
              <label>Tema (opcional)</label>
              <input
                type="text"
                value={entryTopic}
                onChange={(e) => setEntryTopic(e.target.value)}
                placeholder="p. ej. Tema 3: Termodinámica"
              />
            </div>
            <div className="field" style={{ marginBottom: 8 }}>
              <label>Horas a dedicar</label>
              <div className="wrap-chips">
                {DURATION_PRESETS.map((m) => (
                  <button
                    type="button"
                    key={m}
                    className={`pill-btn${entryMinutes === m ? ' selected' : ''}`}
                    onClick={() => setEntryMinutes(m)}
                  >
                    {m < 60 ? `${m} min` : `${m / 60} h`}
                  </button>
                ))}
              </div>
            </div>
            {remainingFreeForDate(entryDate) < entryMinutes && (
              <div className="warning-box" style={{ marginBottom: 10 }}>
                ⚠️ Ese día ({weekdayName(entryDate)}) solo te quedan{' '}
                {formatDurationMinutes(Math.max(0, remainingFreeForDate(entryDate)))} libres según tu disponibilidad.
              </div>
            )}
            <button type="button" className="btn btn-secondary" onClick={addEntry}>
              + Añadir sesión
            </button>
          </div>

          {sortedEntries.length > 0 && (
            <div className="card" style={{ marginBottom: 14 }}>
              <div style={{ fontWeight: 700, marginBottom: 8 }}>Tu plan</div>
              <div className="list-gap">
                {sortedEntries.map((e) => (
                  <div key={e.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8 }}>
                    <div style={{ fontSize: '0.88rem' }}>
                      <div style={{ fontWeight: 600 }}>
                        {weekdayName(e.date)} {formatShort(e.date)}
                      </div>
                      {e.topic && <div className="muted">{e.topic}</div>}
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span className="chip">{formatDurationMinutes(e.minutes)}</span>
                      <button
                        type="button"
                        onClick={() => removeEntry(e.id)}
                        style={{ border: 'none', background: 'none', color: 'var(--danger)', fontSize: '1.1rem' }}
                        aria-label="Quitar"
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: 10, fontSize: '0.85rem' }} className="muted">
                Total: {formatDurationMinutes(manualTotalMinutes)}
              </div>
            </div>
          )}

          <button className="btn btn-primary" onClick={handleConfirmManual} disabled={entries.length === 0}>
            Guardar mi plan de estudio
          </button>
        </>
      )}
    </div>
  )
}
