import React, { useState } from 'react'
import type { Importance, ItemType, TaskItem, TaskStatus } from '../../types'
import { ITEM_TYPES } from '../../types'
import { makeId } from '../../lib/id'
import { useData } from '../../context/DataContext'

const DURATION_PRESETS = [15, 30, 45, 60, 90, 120, 180]

export function TaskForm({
  initial,
  onSaved,
  onCancel,
}: {
  initial?: TaskItem
  onSaved: (t: TaskItem) => void
  onCancel: () => void
}) {
  const { addTask, updateTask, deleteTask } = useData()
  const isEdit = !!initial

  const [title, setTitle] = useState(initial?.title ?? '')
  const [category, setCategory] = useState<ItemType>(initial?.category ?? 'personal')
  const [hasDueDate, setHasDueDate] = useState(!!initial?.dueDate)
  const [dueDate, setDueDate] = useState(initial?.dueDate ?? '')
  const [duration, setDuration] = useState(initial?.estimatedMinutes ?? 60)
  const [priority, setPriority] = useState<Importance>(initial?.priority ?? 2)
  const [status, setStatus] = useState<TaskStatus>(initial?.status ?? 'pendiente')
  const [notes, setNotes] = useState(initial?.notes ?? '')

  const canSave = title.trim().length > 0

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!canSave) return
    const task: TaskItem = {
      id: initial?.id ?? makeId(),
      kind: 'task',
      title: title.trim(),
      category,
      dueDate: hasDueDate ? dueDate || undefined : undefined,
      estimatedMinutes: duration,
      priority,
      status,
      scheduledDate: initial?.scheduledDate,
      scheduledStart: initial?.scheduledStart,
      scheduledEnd: initial?.scheduledEnd,
      notes: notes.trim() || undefined,
      linkedEventId: initial?.linkedEventId,
      isAutoGenerated: initial?.isAutoGenerated,
      goalId: initial?.goalId,
      createdAt: initial?.createdAt ?? new Date().toISOString(),
      remindersFired: initial?.remindersFired ?? [],
    }
    if (isEdit) updateTask(task.id, task)
    else addTask(task)
    onSaved(task)
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="field">
        <label>Nombre</label>
        <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="p. ej. Hacer ejercicios de Sistemas" autoFocus />
      </div>

      <div className="field">
        <label>Categoría</label>
        <div className="wrap-chips">
          {ITEM_TYPES.map((t) => (
            <button type="button" key={t.value} className={`pill-btn${category === t.value ? ' selected' : ''}`} onClick={() => setCategory(t.value)}>
              {t.emoji} {t.label}
            </button>
          ))}
        </div>
      </div>

      <div className="field">
        <label>
          <input type="checkbox" checked={hasDueDate} onChange={(e) => setHasDueDate(e.target.checked)} /> Tiene fecha límite
        </label>
      </div>
      {hasDueDate && (
        <div className="field">
          <label>Fecha límite</label>
          <input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
        </div>
      )}

      <div className="field">
        <label>Duración estimada</label>
        <div className="wrap-chips">
          {DURATION_PRESETS.map((m) => (
            <button type="button" key={m} className={`pill-btn${duration === m ? ' selected' : ''}`} onClick={() => setDuration(m)}>
              {m < 60 ? `${m} min` : `${m / 60} h`}
            </button>
          ))}
        </div>
      </div>

      <div className="field">
        <label>Prioridad</label>
        <div className="wrap-chips">
          {([1, 2, 3, 4] as Importance[]).map((imp) => (
            <button type="button" key={imp} className={`pill-btn${priority === imp ? ' selected' : ''}`} onClick={() => setPriority(imp)}>
              {{ 1: 'Baja', 2: 'Media', 3: 'Alta', 4: 'Crítica' }[imp]}
            </button>
          ))}
        </div>
      </div>

      {isEdit && (
        <div className="field">
          <label>Estado</label>
          <div className="wrap-chips">
            {(
              [
                ['pendiente', 'Pendiente'],
                ['en_progreso', 'En progreso'],
                ['completada', 'Completada'],
              ] as [TaskStatus, string][]
            ).map(([v, label]) => (
              <button type="button" key={v} className={`pill-btn${status === v ? ' selected' : ''}`} onClick={() => setStatus(v)}>
                {label}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="field">
        <label>Notas</label>
        <textarea value={notes} onChange={(e) => setNotes(e.target.value)} />
      </div>

      <button className="btn btn-primary" type="submit" disabled={!canSave}>
        {isEdit ? 'Guardar cambios' : 'Crear tarea'}
      </button>

      {isEdit && initial && (
        <button
          type="button"
          className="btn btn-danger"
          style={{ marginTop: 10 }}
          onClick={() => {
            deleteTask(initial.id)
            onCancel()
          }}
        >
          Eliminar tarea
        </button>
      )}
    </form>
  )
}
